### ISSUE TITLE
Improve config error messages

### ISSUE THREAD

**Issue by zuhanit** [armoha/euddraft#54]
Error messages of euddraft just print line and error, but it takes a little time to find error.

Here's the error messages of current euddraft.
```
Traceback (most recent call last):
  File "C:\Py\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 113, in run
  File "C:\Py\Lib\site-packages\cx_Freeze\initscripts\Console.py", line 15, in run
  File "euddraft.py", line 151, in <module>
  File "E:\euddraft\readconfig.py", line 114, in readconfig
  File "E:\euddraft\readconfig.py", line 55, in parse_config
RuntimeError: ('Duplicate header [main]', '[Line 1] [main]', '[Line 3] [main]')
```

And here's error messages of TypeScript for example, an Type Error. it provides actual user codes and point out what makes error.

```
python-runtime-error/duplicated-identifier.ts:1:7 - error TS2322: Type 'number' is not assignable to type 'string'.

1 const foo: string = 1;
        ~~~


Found 1 error.
```

Maybe fix error messages like below will better to user.
```
...
RuntimeError: ('
Duplicate header 'main'
1 [main]
  ~~~~~~
2 [main]
  ~~~~~~
')

**Comment by armoha** [comment]
Fixed by #55
